# Generated by Django 2.1.5 on 2020-08-02 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='usuario',
        ),
        migrations.AddField(
            model_name='entrada',
            name='UserPerchero',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserPerchero'),
        ),
        migrations.AddField(
            model_name='perchado',
            name='UserPerchero',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserPerchero'),
        ),
        migrations.AddField(
            model_name='salida',
            name='UserPerchero',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserPerchero'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
