# Generated by Django 2.1.2 on 2020-08-01 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='Descripcion',
            new_name='Descripcin',
        ),
    ]
