# Generated by Django 2.1.2 on 2020-07-11 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200710_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextra',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserExtra',
        ),
    ]
