# Generated by Django 2.1.5 on 2020-08-02 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_perchado_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perchado',
            name='ubicacion',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
