# Generated by Django 2.1.2 on 2020-07-11 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_despacho_recibo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo_p',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_Recibo', models.CharField(max_length=200)),
                ('Proovedor', models.CharField(max_length=200)),
                ('Usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
