# Generated by Django 2.1.5 on 2020-08-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ubication'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubication',
            name='Estado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ubication',
            name='Nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
