# Generated by Django 2.1.2 on 2020-07-11 20:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_recibo_p'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recibo',
            new_name='Producto',
        ),
    ]
