# Generated by Django 2.1.5 on 2020-08-02 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200802_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='perchado',
            name='ubication',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ubication'),
        ),
        migrations.AddField(
            model_name='salida',
            name='fecha',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='perchado',
            name='fecha',
            field=models.DateField(default=None),
        ),
    ]
