# Generated by Django 2.1.5 on 2020-08-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200802_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='existencia',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='UnidadesExistencia',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Existencia',
        ),
    ]
