# Generated by Django 2.1.2 on 2020-07-29 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200711_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proovedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='Usuario_asignado',
        ),
        migrations.RemoveField(
            model_name='recibo_p',
            name='Usuario_asignado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Ubicación',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Usuario_asignado',
        ),
        migrations.AddField(
            model_name='producto',
            name='Codigo_barra',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='producto',
            name='Estado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='Nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='Precio',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='Despacho',
        ),
        migrations.DeleteModel(
            name='Recibo_p',
        ),
        migrations.AddField(
            model_name='producto',
            name='Proovedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Proovedor'),
        ),
    ]
