# Generated by Django 2.1.2 on 2020-07-30 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200729_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Proovedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Proovedor'),
        ),
    ]
