# Generated by Django 2.1.5 on 2020-08-21 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200817_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='entrega',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Entrada'),
        ),
        migrations.AddField(
            model_name='producto',
            name='perchado',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Perchado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='salida',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Salida'),
        ),
    ]
